change restore from job to cronjob, apply revised template using jq in github action such that restore date can be specified

diff --git a/infra/base/templates/restore-prod-mongo.yaml b/infra/base/templates/restore-prod-mongo.yaml
--- a/infra/base/templates/restore-prod-mongo.yaml
+++ b/infra/base/templates/restore-prod-mongo.yaml
@@ -1,53 +1,57 @@
 apiVersion: batch/v1
-kind: Job
+kind: CronJob
 metadata:
   name: {{ .Release.Name }}-restore-prod-mongo
   namespace: bt
 spec:
-  ttlSecondsAfterFinished: 180
-  template:
+  schedule: "0 5 * * *" # Daily at 5 AM
+  timeZone: America/Los_Angeles
+  concurrencyPolicy: Forbid
+  suspend: true # disable scheduled runs
+  jobTemplate:
     spec:
-      serviceAccountName: bt-k8s-role
-      containers:
-        - name: backup-prod-mongo
-          image: alpine/k8s:1.29.11
-          command:
-            - /bin/sh
-            - -c
-            - |
-              set -e # Exit immediately if a command fails
+      ttlSecondsAfterFinished: 180
+      template:
+        spec:
+          serviceAccountName: bt-k8s-role
+          containers:
+            - name: backup-prod-mongo
+              image: alpine/k8s:1.29.11
+              command:
+                - /bin/sh
+                - -c
+                - |
+                  set -e # Exit immediately if a command fails
 
-              # Find production MongoDB pod
-              prod_pod=$(kubectl get pods -o custom-columns=NAME:.metadata.name --no-headers -n bt | grep 'bt-prod-mongo')
+                  # Find production MongoDB pod
+                  prod_pod=$(kubectl get pods -o custom-columns=NAME:.metadata.name --no-headers -n bt | grep 'bt-prod-mongo')
 
-              # Download production MongoDB backup
-              restore_date=${RESTORE_DATE}
-              echo "Downloading backup from s3 bucket..."
-              aws s3 cp s3://$BUCKET_NAME/prod_backup-$restore_date.gz /tmp/prod_backup.gz \
-                --endpoint-url=https://$ACCOUNT_ID.r2.cloudflarestorage.com
+                  # Download production MongoDB backup
+                  restore_date=${RESTORE_DATE}
+                  echo "Downloading backup from s3 bucket..."
+                  aws s3 cp s3://$BUCKET_NAME/prod_backup-$restore_date.gz /tmp/prod_backup.gz \
+                    --endpoint-url=https://$ACCOUNT_ID.r2.cloudflarestorage.com
 
-              # Restore dump into production MongoDB
-              echo "Restoring production MongoDB from backup..."
-              kubectl cp --namespace=bt \
-                /tmp/prod_backup.gz "$prod_pod:/tmp/prod_backup.gz"
-              kubectl exec --namespace=bt \
-                "$prod_pod" -- mongosh bt --eval "db.dropDatabase()"
-              kubectl exec --namespace=bt \
-                "$prod_pod" -- mongorestore --archive=/tmp/prod_backup.gz --gzip --drop
-              kubectl exec --namespace=bt \
-                "$prod_pod" -- rm /tmp/prod_backup.gz
+                  # Restore dump into production MongoDB
+                  echo "Restoring production MongoDB from backup..."
+                  kubectl cp --namespace=bt \
+                    /tmp/prod_backup.gz "$prod_pod:/tmp/prod_backup.gz"
+                  kubectl exec --namespace=bt \
+                    "$prod_pod" -- mongosh bt --eval "db.dropDatabase()"
+                  kubectl exec --namespace=bt \
+                    "$prod_pod" -- mongorestore --archive=/tmp/prod_backup.gz --gzip --drop
+                  kubectl exec --namespace=bt \
+                    "$prod_pod" -- rm /tmp/prod_backup.gz
 
-              # Cleanup local files
-              rm /tmp/prod_backup.gz
-              echo "MongoDB restore completed successfully!"
-          env:
-            - name: ACCOUNT_ID
-              value: ff660bd2dac18c00551ed509d24ef4d7
-            - name: BUCKET_NAME
-              value: prod-mongo-backups
-            - name: RESTORE_DATE
-              value: "${RESTORE_DATE}"
-          envFrom:
-            - secretRef:
-                name: cloudflare-prod-mongo-secret
-      restartPolicy: Never
+                  # Cleanup local files
+                  rm /tmp/prod_backup.gz
+                  echo "MongoDB restore completed successfully!"
+              env:
+                - name: ACCOUNT_ID
+                  value: ff660bd2dac18c00551ed509d24ef4d7
+                - name: BUCKET_NAME
+                  value: prod-mongo-backups
+              envFrom:
+                - secretRef:
+                    name: cloudflare-prod-mongo-secret
+          restartPolicy: Never
