staging and production

diff --git a/.github/workflows/cd-prod.yaml b/.github/workflows/cd-prod.yaml
--- a/.github/workflows/cd-prod.yaml
+++ b/.github/workflows/cd-prod.yaml
@@ -1,6 +1,6 @@
 name: Deploy to Production
 
-concurrency: prod
+concurrency: production
 
 on:
   workflow_dispatch:
@@ -16,40 +16,37 @@ jobs:
         run: echo "Passed check"
 
   build-push:
-    name: Build and Push Images
+    name: Build and Push Images and Charts
     needs: [branch-check]
     uses: ./.github/workflows/cd.yaml
     with:
-      tag: prod
+      image_tag: prod
+      chart_ver: "1.0.0"
     secrets: inherit
 
   deploy:
-    name: Deploy with SSH
+    name: SSH and Deploy
     needs: [build-push]
-    runs-on: ubuntu-latest
+    uses: ./.github/workflows/deploy.yaml
+    with:
+      environment: production
+      script: |
+        set -e  # Exit immediately if a command fails
+        cd ./infra
 
-    steps:
-      - name: SSH and Helm Install
-        uses: appleboy/ssh-action@v1.2.0
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: root
-          key: ${{ secrets.SSH_KEY }}
-          script: |
-            set -e  # Exit immediately if a command fails
-            cd ./infra
+        # Check if the Helm release exists
+        if helm status bt-prod-app ; then
+          # Restart deployments if the Helm release exists
+          kubectl rollout restart deployment bt-prod-app-backend
+          kubectl rollout restart deployment bt-prod-app-frontend
+        else
+          # Install the Helm release if it doesn't exist
+          helm install bt-prod-app oci://registry-1.docker.io/octoberkeleytime/bt-app \
+            --version=1.0.0 \
+            --namespace=bt \
+            --set host=stanfurdtime.com
+        fi
 
-            # Check if the Helm release exists
-            if helm status bt-prod-app ; then
-              # Restart deployments if the Helm release exists
-              kubectl rollout restart deployment bt-prod-app-backend
-              kubectl rollout restart deployment bt-prod-app-frontend
-            else
-              # Install the Helm release if it doesn't exist
-              helm install bt-prod-app ./app --namespace=bt \
-                --set host=stanfurdtime.com
-            fi
-
-            # Check container status
-            kubectl rollout status --timeout=180s deployment bt-prod-app-backend
-            kubectl rollout status --timeout=180s deployment bt-prod-app-frontend
+        # Check container status
+        kubectl rollout status --timeout=180s deployment bt-prod-app-backend
+        kubectl rollout status --timeout=180s deployment bt-prod-app-frontend
diff --git a/.github/workflows/cd-stage.yaml b/.github/workflows/cd-stage.yaml
--- a/.github/workflows/cd-stage.yaml
+++ b/.github/workflows/cd-stage.yaml
@@ -1,6 +1,6 @@
 name: Deploy to Staging
 
-concurrency: stage
+concurrency: staging
 
 on:
   push:
@@ -8,45 +8,39 @@ on:
 
 jobs:
   build-push:
-    name: Build and Push Images
+    name: Build and Push Images and Charts
     uses: ./.github/workflows/cd.yaml
     with:
-      tag: latest
+      image_tag: latest
+      chart_ver: 0.1.0-stage
     secrets: inherit
 
   deploy:
-    name: Deploy with SSH
+    name: SSH and Deploy
     needs: [build-push]
-    runs-on: ubuntu-latest
-    environment: staging
+    uses: ./.github/workflows/deploy.yaml
+    with:
+      environment: staging
+      script: |
+        set -e  # Exit immediately if a command fails
+        cd ./infra
 
-    steps:
-      - name: SSH and Helm Install
-        uses: appleboy/ssh-action@v1.2.0
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: root
-          key: ${{ secrets.SSH_KEY }}
-          script: |
-            set -e  # Exit immediately if a command fails
-            cd ./infra
+        # Check if the Helm release exists
+        if helm status bt-stage-app ; then
+          # Restart deployments if the Helm release exists
+          kubectl rollout restart deployment bt-stage-app-backend
+          kubectl rollout restart deployment bt-stage-app-frontend
+        else
+          # Install the Helm release if it doesn't exist
+          helm install bt-stage-app ./app --namespace=bt \
+            --set env=stage \
+            --set frontend.image.tag=latest \
+            --set backend.image.tag=latest \
+            --set host=staging.stanfurdtime.com \
+            --set mongoUri=mongodb://bt-stage-mongo-mongodb.bt.svc.cluster.local:27017/bt \
+            --set redisUri=redis://bt-stage-redis-master.bt.svc.cluster.local:6379
+        fi
 
-            # Check if the Helm release exists
-            if helm status bt-stage-app ; then
-              # Restart deployments if the Helm release exists
-              kubectl rollout restart deployment bt-stage-app-backend
-              kubectl rollout restart deployment bt-stage-app-frontend
-            else
-              # Install the Helm release if it doesn't exist
-              helm install bt-stage-app ./app --namespace=bt \
-                --set env=stage \
-                --set frontend.image.tag=latest \
-                --set backend.image.tag=latest \
-                --set host=staging.stanfurdtime.com \
-                --set mongoUri=mongodb://bt-stage-mongo-mongodb.bt.svc.cluster.local:27017/bt \
-                --set redisUri=redis://bt-stage-redis-master.bt.svc.cluster.local:6379
-            fi
-
-            # Check container status
-            kubectl rollout status --timeout=180s deployment bt-stage-app-backend
-            kubectl rollout status --timeout=180s deployment bt-stage-app-frontend
+        # Check container status
+        kubectl rollout status --timeout=180s deployment bt-stage-app-backend
+        kubectl rollout status --timeout=180s deployment bt-stage-app-frontend
